source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MetaBrowser' do
  pod 'Alamofire', '~> 4.7'
  pod 'R.swift'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SDWebImage', '~> 4.0'
  pod "MapleBacon"
end
